Revert Wayland changes and add additional permissions
flathub/com.slack.Slack pull request #213
Opened 2023-08-17 02:51 UTC by evan-a-a

* Revert wayland by default (fixes #212, #211, #210)
* Convert to yaml manifest
* Address missing dbus permissions. Slack now requires access to session secrets manager and system login dbus interfaces. Add `xdg-download` permissions to fix file downloads not appearing in the download folder (fixes #202, #193)

2023-08-20 10:36 UTC, razzeee commented
Testing this, it seems to behave even worse for me. But it seems to fix #210

But it locks the window from being moved by mouse completely? And I still don't get a window close `x` button.

Getting this in the settings, but don't know if it's new.
```
LaunchProcess: failed to execvp:
xdg-settings
```

This is running recent fedora with wayland.

2023-08-20 15:28 UTC, evan-a-a commented
@razzeee, Can you try the new test build? I missed the x11 socket permission.

I did notice the xdg-settings message but I haven't noticed what functionality it impacts. It also doesn't seem to be related to the display sockets.

2023-08-20 15:56 UTC, razzeee commented
Seems to fix all my problems.

- Close, maximize, minimize buttons are back
- I can move the window around
- The new external threads windows can be closed
- Mouse cursor isn't upside down anymore https://github.com/flathub/com.slack.Slack/issues/182
- Scrollbars are back when halved

2023-08-22 16:55 UTC, brittyazel commented
Agreed with what @razzeee said above. This PR solved all of my issues.

2023-08-23 14:09 UTC, hfiguiere commented
i'd love to help merging this but you have made the PR unreviewable by switching the manifest format for no reason.

2023-08-24 08:48 UTC, Leniwcowaty commented
Please merge it ASAP, this really messes up my workflow :(

2023-08-24 10:23 UTC, monosoul commented
People having troubles with the latest flatpak version can run this command to revert to the previous version:
```shell
sudo flatpak update --commit=ce966b70820ed5191a91273641042fafac5df33eb85af0609ecb482f0cdb1b44 com.slack.Slack
```

2023-08-24 17:07 UTC, hfiguiere requested changes
This PR unecessarily change the format of the manifest.

2023-08-24 20:24 UTC, hfiguiere approved these changes

2023-08-24 20:25 UTC, merged